// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://leojvuxyvamdrgsfxzzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxlb2p2dXh5dmFtZHJnc2Z4enpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NzMwNDYsImV4cCI6MjA2OTI0OTA0Nn0.iLeigHIaXek_uEmj9OO7KLzSId-3dkROhrwhd__tvMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});